The task_DEV-3 project files were added.
MariaEroshevich/TAT-2018 pull request #3
Opened 2018-03-07 16:08 UTC by MariaEroshevich

2018-03-07 18:08 UTC, IgorKheidorov requested changes

2018-03-07 18:08 UTC, IgorKheidorov commented on task_DEV-3/EntryPoint.cs
> +      {
Check for number of input arguments

2018-03-07 18:08 UTC, IgorKheidorov commented on task_DEV-3/NumberConverter.cs
> +    {
What about decimalNumber =0?

2018-03-07 18:08 UTC, IgorKheidorov commented on task_DEV-3/NumberConverter.cs
> +      {
Good, very compact

2018-03-07 18:08 UTC, IgorKheidorov commented on task_DEV-3/NumberConverter.cs
> +    {
Why decimalNumber = 0 is exception? It is normal number

2018-03-08 19:30 UTC, AlexanderSoroka approved these changes

2018-03-08 19:30 UTC, AlexanderSoroka commented on task_DEV-3/EntryPoint.cs
> +      {
Actually it's useless check - see chat for my point

2018-03-12 11:41 UTC, merged